fields:
  source: node-metrics

metricbeat.modules:

- module: system
  metricsets: ["cpu", "diskio", "filesystem", "fsstat", "load", "memory", "network", "process_summary", "socket_summary", "uptime"]
  enabled: true
  period: 30s
  processes: ['.*']
  cpu.metrics:  ["normalized_percentages"]
  core.metrics: ["percentages"]

- module: docker
  metricsets: ["cpu", "diskio", "healthcheck", "info", "memory", "network"]
  cpu.cores: false
  hosts: ["unix:///var/run/docker.sock"]
  period: 30s

#- module: docker
#  metricsets:
#  - container
#  hosts: ["unix:///var/run/docker.sock"]
#  period: 1m

output.console:
  enabled: true
  pretty: false

output.elasticsearch:
  enabled: false
  hosts: 'elasticsearch:9200'

setup.kibana.host: "kibana:5601"
setup.dashboards.enabled: false

output.kafka:
  enabled: false
  hosts: "kafka:9092"
  topic: 'es_filebeat_kafka'
  version: "2.0.0"
  partition.round_robin:
    reachable_only: false

  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000

logging.level: ${ES_METRICBEAT_LOGGING_LEVEL:warning}
logging.metrics.enabled: false
logging.metrics.period: 30s
logging.json: false
