#!/usr/bin/env bash

prefix="vcw_module_hkvb_elastic_journalbeat__$1"
prefix="vcw_module_hkvb_elastic_journalbeat__$1"

if [[ "vcw_module_hkvb_elastic_journalbeat__journal_config" == "$prefix"* ]] ; then
	executionplane --silent docker volume create vcw_module_hkvb_elastic_journalbeat__journal_config
fi

if [[ "vcw_module_hkvb_elastic_journalbeat__journal_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create vcw_module_hkvb_elastic_journalbeat__journal_volume
fi

if [[ "vcw_module_hkvb_elastic_journalbeat__journal_config" == "$prefix"* ]] ; then
	executionplane --silent docker run -v vcw_infometis_repos:/source -v vcw_module_hkvb_elastic_journalbeat__journal_config:/vcw/pwd ${VCW_REGISTRY}hkvb/infometis console cmd cp -r /source/hkvb/elastic/journalbeat/_module/volumes/journal_config/* /vcw/pwd
fi
