#!/usr/bin/env bash

prefix="vcw_module_hkvb_elastic_journalbeat__$1"
prefix="vcw_module_hkvb_elastic_journalbeat__$1"

executionplane --silent docker container prune --force

if [[ "vcw_module_hkvb_elastic_journalbeat__journal_config" == "$prefix"* ]] ; then
	continue="true"
	while [[ "true" == "$continue" ]] ;
	do
		executionplane docker volume rm "vcw_module_hkvb_elastic_journalbeat__journal_config"
		result=$(docker volume ls | grep "vcw_module_hkvb_elastic_journalbeat__journal_config")
		if [[ "$result" == "" ]] ; then
			continue="false"
		else
			sleep 3;
		fi
	done;
fi

if [[ "vcw_module_hkvb_elastic_journalbeat__journal_entrypoint" == "$prefix"* ]] ; then
	continue="true"
	while [[ "true" == "$continue" ]] ;
	do
		executionplane docker volume rm "vcw_module_hkvb_elastic_journalbeat__journal_entrypoint"
		result=$(docker volume ls | grep "vcw_module_hkvb_elastic_journalbeat__journal_entrypoint")
		if [[ "$result" == "" ]] ; then
			continue="false"
		else
			sleep 3;
		fi
	done;
fi

if [[ "vcw_module_hkvb_elastic_journalbeat__journal_volume" == "$prefix"* ]] ; then
	continue="true"
	while [[ "true" == "$continue" ]] ;
	do
		executionplane docker volume rm "vcw_module_hkvb_elastic_journalbeat__journal_volume"
		result=$(docker volume ls | grep "vcw_module_hkvb_elastic_journalbeat__journal_volume")
		if [[ "$result" == "" ]] ; then
			continue="false"
		else
			sleep 3;
		fi
	done;
fi
