#!/usr/bin/env bash

executionplane --silent docker container prune --force
continue="true"
while [[ "true" == "$continue" ]] ;
do
	executionplane docker volume rm "hkvb_swarm_monitor__elastic_volume"
	result=$(docker volume ls | grep "hkvb_swarm_monitor__elastic_volume")
	if [[ "$result" == "" ]] ; then
		continue="false"
	else
		sleep 3;
	fi
done;
	
continue="true"
while [[ "true" == "$continue" ]] ;
do
	executionplane docker volume rm "hkvb_swarm_monitor__grafana_volume"
	result=$(docker volume ls | grep "hkvb_swarm_monitor__grafana_volume")
	if [[ "$result" == "" ]] ; then
		continue="false"
	else
		sleep 3;
	fi
done;
	
continue="true"
while [[ "true" == "$continue" ]] ;
do
	executionplane docker volume rm "hkvb_swarm_monitor__kafka_secrets_volume"
	result=$(docker volume ls | grep "hkvb_swarm_monitor__kafka_secrets_volume")
	if [[ "$result" == "" ]] ; then
		continue="false"
	else
		sleep 3;
	fi
done;
	
continue="true"
while [[ "true" == "$continue" ]] ;
do
	executionplane docker volume rm "hkvb_swarm_monitor__kafka_data_volume"
	result=$(docker volume ls | grep "hkvb_swarm_monitor__kafka_data_volume")
	if [[ "$result" == "" ]] ; then
		continue="false"
	else
		sleep 3;
	fi
done;
	
continue="true"
while [[ "true" == "$continue" ]] ;
do
	executionplane docker volume rm "hkvb_swarm_monitor__ksqldb_queries_volume"
	result=$(docker volume ls | grep "hkvb_swarm_monitor__ksqldb_queries_volume")
	if [[ "$result" == "" ]] ; then
		continue="false"
	else
		sleep 3;
	fi
done;
	
continue="true"
while [[ "true" == "$continue" ]] ;
do
	executionplane docker volume rm "hkvb_swarm_monitor__schema_registry_secrets_volume"
	result=$(docker volume ls | grep "hkvb_swarm_monitor__schema_registry_secrets_volume")
	if [[ "$result" == "" ]] ; then
		continue="false"
	else
		sleep 3;
	fi
done;
	
continue="true"
while [[ "true" == "$continue" ]] ;
do
	executionplane docker volume rm "hkvb_swarm_monitor__streamsets_volume"
	result=$(docker volume ls | grep "hkvb_swarm_monitor__streamsets_volume")
	if [[ "$result" == "" ]] ; then
		continue="false"
	else
		sleep 3;
	fi
done;
	
continue="true"
while [[ "true" == "$continue" ]] ;
do
	executionplane docker volume rm "hkvb_swarm_monitor__zookeeper_secrets_volume"
	result=$(docker volume ls | grep "hkvb_swarm_monitor__zookeeper_secrets_volume")
	if [[ "$result" == "" ]] ; then
		continue="false"
	else
		sleep 3;
	fi
done;
	
continue="true"
while [[ "true" == "$continue" ]] ;
do
	executionplane docker volume rm "hkvb_swarm_monitor__zookeeper_data_volume"
	result=$(docker volume ls | grep "hkvb_swarm_monitor__zookeeper_data_volume")
	if [[ "$result" == "" ]] ; then
		continue="false"
	else
		sleep 3;
	fi
done;
	
continue="true"
while [[ "true" == "$continue" ]] ;
do
	executionplane docker volume rm "hkvb_swarm_monitor__zookeeper_log_volume"
	result=$(docker volume ls | grep "hkvb_swarm_monitor__zookeeper_log_volume")
	if [[ "$result" == "" ]] ; then
		continue="false"
	else
		sleep 3;
	fi
done;
	
