#!/usr/bin/env bash

executionplane --silent docker volume create hkvb_swarm__monitor__elastic_volume
	
executionplane --silent docker volume create hkvb_swarm__monitor__grafana_volume
	
executionplane --silent docker volume create hkvb_swarm__monitor__kafka_secrets_volume
	
executionplane --silent docker volume create hkvb_swarm__monitor__kafka_data_volume
	
executionplane --silent docker volume create hkvb_swarm__monitor__ksqldb_queries_volume
	
executionplane --silent docker volume create hkvb_swarm__monitor__schema_registry_secrets_volume
	
executionplane --silent docker volume create hkvb_swarm__monitor__streamsets_volume
	
executionplane --silent docker volume create hkvb_swarm__monitor__zookeeper_secrets_volume
	
executionplane --silent docker volume create hkvb_swarm__monitor__zookeeper_data_volume
	
executionplane --silent docker volume create hkvb_swarm__monitor__zookeeper_log_volume
	

executionplane --silent docker run -v vcw_infometis_repos:/source -v hkvb_swarm__monitor__elastic_volume:/usr/share/elasticsearch/data ${VCW_REGISTRY}hkvb/infometis console untar /source/hkvb/swarm/monitor/_solution/_configuration/volumes/elastic_volume.tar


executionplane --silent docker run -v vcw_infometis_repos:/source -v hkvb_swarm__monitor__grafana_volume:/var/lib/grafana ${VCW_REGISTRY}hkvb/infometis console untar /source/hkvb/swarm/monitor/_solution/_configuration/volumes/grafana_volume.tar


executionplane --silent docker run -v vcw_infometis_repos:/source -v hkvb_swarm__monitor__ksqldb_queries_volume:/vcw/pwd ${VCW_REGISTRY}hkvb/infometis console cmd cp -r /source/hkvb/swarm/monitor/_solution/_configuration/volumes/ksqldb_queries_volume/* /vcw/pwd


executionplane --silent docker run -v vcw_infometis_repos:/source -v hkvb_swarm__monitor__streamsets_volume:/data ${VCW_REGISTRY}hkvb/infometis console untar /source/hkvb/swarm/monitor/_solution/_configuration/volumes/streamsets_volume.tar

