#!/usr/bin/env bash

executionplane-info "EXECUTING CONTROLPLANE DEPLOY"

.solution deploy --recurse $@

.solution run boot --recurse $@

sleep 30

.solution run start monitor/logs $@
.solution run start monitor/metrics_node $@
.solution run start monitor/metrics_overlay $@
.solution run start monitor $@

sleep 60

.solution run start monitor/controlcenter $@
