---
version: '3'
services:

# START SERVICE hkvb/confluent/kafka
  kafka:
    image: ${VCW_REGISTRY}confluentinc/cp-kafka:6.1.1
    environment: ['KAFKA_HEAP_OPTS=-Xmx${KAFKA_DEPLOY_RESOURCES_RESERVATIONS_MEMORY} -Xms${KAFKA_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}','KAFKA_BROKER_ID=1','KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181','KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092${KAFKA_KAFKA_ADVERTISED_LISTENERS}','KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT${KAFKA_KAFKA_LISTENER_SECURITY_PROTOCOL_MAP}','KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT','KAFKA_AUTO_CREATE_TOPICS_ENABLE=true','KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1','KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0','KAFKA_MIN_INSYNC_REPLICAS=1','KAFKA_DEFAULT_REPLICATION_FACTOR=1','KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1','KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1','KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR=1','CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS=kafka:9092','CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT=zookeeper:2181','CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS=1','CONFLUENT_METRICS_ENABLE=true','CONFLUENT_SUPPORT_CUSTOMER_ID=anonymous','KAFKA_LOG_RETENTION_HOURS=1', 'KAFKA_LOG_CLEANER_ENABLE=true', 'KAFKA_LOG_CLEANUP_POLICY=delete' ${KAFKA_ENVIRONMENT_EXTRA}]
    command: []
    volumes: ['${VCW_STACK_GLOBAL_STACKPREFIX}_secrets_volume:/etc/kafka/secrets','${VCW_STACK_GLOBAL_STACKPREFIX}_data_volume:/var/lib/kafka/data']
    ports: [${KAFKA_PORTS}]
    networks: [${VCW_STACK_GLOBAL_NETWORKLOCAL}_overlay]
    deploy:
      mode: replicated
      resources:
        limits:
          memory: '${KAFKA_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          memory: '${KAFKA_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
${KAFKA_COMPOSE_EXTENSIONS}
# END SERVICE hkvb/confluent/kafka

networks: {${VCW_STACK_GLOBAL_NETWORKLOCAL}_overlay: { external: true }}
volumes: {${VCW_STACK_GLOBAL_STACKPREFIX}_secrets_volume: { external: true },${VCW_STACK_GLOBAL_STACKPREFIX}_data_volume: { external: true }}
${VCW_STACK_GLOBAL_COMPOSE_EXTENSIONS}
