#!/usr/bin/env bash

prefix="vcw_module_hkvb_poc_blank__$1"
prefix="vcw_module_hkvb_poc_blank__$1"

if [[ "vcw_module_hkvb_poc_blank__blank_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create vcw_module_hkvb_poc_blank__blank_volume
fi

if [[ "vcw_module_hkvb_poc_blank__blank_volume" == "$prefix"* ]] ; then
	executionplane --silent docker run -v vcw_infometis_repos:/source -v vcw_module_hkvb_poc_blank__blank_volume:/etc/blank ${VCW_REGISTRY}hkvb/infometis console cmd cp -r /source/hkvb/poc/blank/_module/volumes/blank_volume/* /etc/blank
fi
