#!/usr/bin/env bash

      # START COMPONENT CONFIGURATION
DOLLAR='$'
export VCW_SOLUTON_COMPONENT_MODULE="hkvb/poc/blank/module"
export VCW_SOLUTON_HIDE_COMPONENT="false"
# END COMPONENT CONFIGURATION
#!/usr/bin/env bash

 # START MODULE CONFIGURATION
DOLLAR='$'
export VCW_MODULE_PACKAGES="\
module:hkvb/poc/blank/image"
# END MODULE CONFIGURATION
