#!/usr/bin/env bash

executionplane --silent docker volume create hkvb_swarm__blank_volume
	

executionplane --silent docker run -v vcw_infometis_repos:/source -v hkvb_swarm__blank_volume:/etc/blank ${VCW_REGISTRY}hkvb/infometis console cmd cp -r /source/hkvb/swarm/./_solution/_configuration/volumes/blank_volume/* /etc/blank

