#!/usr/bin/env bash

executionplane --silent docker volume create hkvb_swarm__monitor__journal_config
	
executionplane --silent docker volume create hkvb_swarm__monitor__journal_volume
	

executionplane --silent docker run -v vcw_infometis_repos:/source -v hkvb_swarm__monitor__journal_config:/vcw/pwd ${VCW_REGISTRY}hkvb/infometis console cmd cp -r /source/hkvb/swarm/monitor/logs/_solution/_configuration/volumes/journal_config/* /vcw/pwd

