#!/usr/bin/env bash

executionplane --silent docker volume create hkvb_swarm_monitor__journal_config
	
executionplane --silent docker volume create hkvb_swarm_monitor__journal_entrypoint
	
executionplane --silent docker volume create hkvb_swarm_monitor__journal_volume
	

executionplane --silent docker run -v vcw_infometis_repos:/source -v hkvb_swarm_monitor__journal_config:/vcw/pwd ${VCW_REGISTRY}hkvb/infometis console cmd cp -r /source/hkvb/swarm/monitor/logs/_solution/_configuration/volumes/journal_config/* /vcw/pwd


executionplane --silent docker run -v vcw_infometis_repos:/source -v hkvb_swarm_monitor__journal_entrypoint:/vcw/bin ${VCW_REGISTRY}hkvb/infometis console cmd cp -r /source/hkvb/swarm/monitor/logs/_solution/_configuration/volumes/journal_entrypoint/* /vcw/bin

