#!/usr/bin/env bash

prefix="vcw_module_hkvb_elastic_metricbeat_node__$1"
prefix="vcw_module_hkvb_elastic_metricbeat_node__$1"

if [[ "vcw_module_hkvb_elastic_metricbeat_node__metrics_node_config" == "$prefix"* ]] ; then
	executionplane --silent docker volume create vcw_module_hkvb_elastic_metricbeat_node__metrics_node_config
fi

if [[ "vcw_module_hkvb_elastic_metricbeat_node__metrics_node_entrypoint" == "$prefix"* ]] ; then
	executionplane --silent docker volume create vcw_module_hkvb_elastic_metricbeat_node__metrics_node_entrypoint
fi

if [[ "vcw_module_hkvb_elastic_metricbeat_node__metrics_node_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create vcw_module_hkvb_elastic_metricbeat_node__metrics_node_volume
fi

if [[ "vcw_module_hkvb_elastic_metricbeat_node__metrics_node_config" == "$prefix"* ]] ; then
	executionplane --silent docker run -v vcw_infometis_repos:/source -v vcw_module_hkvb_elastic_metricbeat_node__metrics_node_config:/vcw/pwd ${VCW_REGISTRY}hkvb/infometis console cmd cp -r /source/hkvb/elastic/metricbeat/node/_module/volumes/metrics_node_config/* /vcw/pwd
fi

if [[ "vcw_module_hkvb_elastic_metricbeat_node__metrics_node_entrypoint" == "$prefix"* ]] ; then
	executionplane --silent docker run -v vcw_infometis_repos:/source -v vcw_module_hkvb_elastic_metricbeat_node__metrics_node_entrypoint:/vcw/bin ${VCW_REGISTRY}hkvb/infometis console cmd cp -r /source/hkvb/elastic/metricbeat/node/_module/volumes/metrics_node_entrypoint/* /vcw/bin
fi
