#!/usr/bin/env bash

prefix="vcw_module_hkvb_elastic_metricbeat_node__$1"
prefix="vcw_module_hkvb_elastic_metricbeat_node__$1"

executionplane --silent docker container prune --force

if [[ "vcw_module_hkvb_elastic_metricbeat_node__metrics_node_config" == "$prefix"* ]] ; then
	continue="true"
	while [[ "true" == "$continue" ]] ;
	do
		executionplane docker volume rm "vcw_module_hkvb_elastic_metricbeat_node__metrics_node_config"
		result=$(docker volume ls | grep "vcw_module_hkvb_elastic_metricbeat_node__metrics_node_config")
		if [[ "$result" == "" ]] ; then
			continue="false"
		else
			sleep 3;
		fi
	done;
fi

if [[ "vcw_module_hkvb_elastic_metricbeat_node__metrics_node_entrypoint" == "$prefix"* ]] ; then
	continue="true"
	while [[ "true" == "$continue" ]] ;
	do
		executionplane docker volume rm "vcw_module_hkvb_elastic_metricbeat_node__metrics_node_entrypoint"
		result=$(docker volume ls | grep "vcw_module_hkvb_elastic_metricbeat_node__metrics_node_entrypoint")
		if [[ "$result" == "" ]] ; then
			continue="false"
		else
			sleep 3;
		fi
	done;
fi

if [[ "vcw_module_hkvb_elastic_metricbeat_node__metrics_node_volume" == "$prefix"* ]] ; then
	continue="true"
	while [[ "true" == "$continue" ]] ;
	do
		executionplane docker volume rm "vcw_module_hkvb_elastic_metricbeat_node__metrics_node_volume"
		result=$(docker volume ls | grep "vcw_module_hkvb_elastic_metricbeat_node__metrics_node_volume")
		if [[ "$result" == "" ]] ; then
			continue="false"
		else
			sleep 3;
		fi
	done;
fi
