#!/usr/bin/env bash

prefix="vcw_module_hkvb_poc_elastickafka__$1"
prefix="vcw_module_hkvb_poc_elastickafka__$1"

if [[ "vcw_module_hkvb_poc_elastickafka__elastic_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create vcw_module_hkvb_poc_elastickafka__elastic_volume
fi

if [[ "vcw_module_hkvb_poc_elastickafka__grafana_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create vcw_module_hkvb_poc_elastickafka__grafana_volume
fi

if [[ "vcw_module_hkvb_poc_elastickafka__kafka_secrets_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create vcw_module_hkvb_poc_elastickafka__kafka_secrets_volume
fi

if [[ "vcw_module_hkvb_poc_elastickafka__kafka_data_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create vcw_module_hkvb_poc_elastickafka__kafka_data_volume
fi

if [[ "vcw_module_hkvb_poc_elastickafka__ksqldb_queries_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create vcw_module_hkvb_poc_elastickafka__ksqldb_queries_volume
fi

if [[ "vcw_module_hkvb_poc_elastickafka__schema_registry_secrets_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create vcw_module_hkvb_poc_elastickafka__schema_registry_secrets_volume
fi

if [[ "vcw_module_hkvb_poc_elastickafka__streamsets_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create vcw_module_hkvb_poc_elastickafka__streamsets_volume
fi

if [[ "vcw_module_hkvb_poc_elastickafka__zookeeper_secrets_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create vcw_module_hkvb_poc_elastickafka__zookeeper_secrets_volume
fi

if [[ "vcw_module_hkvb_poc_elastickafka__zookeeper_data_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create vcw_module_hkvb_poc_elastickafka__zookeeper_data_volume
fi

if [[ "vcw_module_hkvb_poc_elastickafka__zookeeper_log_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create vcw_module_hkvb_poc_elastickafka__zookeeper_log_volume
fi
